development:
  MONGOLAB_URI: mongodb://localhost:27017/%APP_NAME-development
  REDISCLOUD_URL: redis://localhost:6379
test:
  MONGOLAB_URI: mongodb://localhost:27017/%APP_NAME-test
  REDISCLOUD_URL: redis://localhost:6379
production:
